# Generated by Django 5.2.1 on 2025-05-15 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, verbose_name='usuario')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('ip', models.CharField(max_length=15, verbose_name='ip')),
                ('web_ip', models.CharField(max_length=15, verbose_name='web_ip')),
                ('clave', models.CharField(max_length=255, verbose_name='clave')),
            ],
        ),
        migrations.CreateModel(
            name='TokenRecuperacionTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, verbose_name='usuario')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
                ('fecha_gen', models.DateTimeField(verbose_name='fecha_gen')),
                ('usado', models.SmallIntegerField(verbose_name='usado')),
            ],
        ),
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('diskid', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='diskid')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('size', models.BigIntegerField(verbose_name='size')),
                ('uso', models.BigIntegerField(null=True, verbose_name='uso')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.planillausuarios', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('network', models.CharField(max_length=30, verbose_name='network')),
                ('dhcp', models.CharField(default=1, max_length=3, verbose_name='dhcp')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.planillausuarios', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachineList',
            fields=[
                ('vmid', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='vmid')),
                ('vmname', models.CharField(max_length=30, verbose_name='vmname')),
                ('cpus', models.IntegerField(verbose_name='cpus')),
                ('ram', models.IntegerField(verbose_name='ram')),
                ('vram', models.IntegerField(verbose_name='vram')),
                ('so', models.CharField(max_length=60, verbose_name='SO')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('estado', models.SmallIntegerField(default=0, verbose_name='estado')),
                ('disco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.discos', verbose_name='disco')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.redes', verbose_name='network')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelos.planillausuarios', verbose_name='usuario')),
            ],
        ),
    ]
