# Generated by Django 4.1.2 on 2023-11-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes',
            name='dhcp',
            field=models.SmallIntegerField(default=1, verbose_name='dhcp'),
        ),
    ]
