# Generated by Django 4.1.2 on 2023-11-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_alter_redes_dhcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachinelist',
            name='disco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.discos', verbose_name='disco'),
        ),
        migrations.AlterField(
            model_name='virtualmachinelist',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Modelos.redes', verbose_name='network'),
        ),
    ]
