# Generated by Django 4.1.2 on 2023-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0003_alter_virtualmachinelist_disco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discos',
            name='uso',
            field=models.BigIntegerField(null=True, verbose_name='uso'),
        ),
    ]
