# Generated by Django 4.1.2 on 2023-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0004_alter_discos_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes',
            name='ipv6',
            field=models.CharField(max_length=100, null=True, verbose_name='ipv6'),
        ),
    ]
