# Generated by Django 4.1.2 on 2023-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0005_alter_redes_ipv6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes',
            name='dhcp',
            field=models.CharField(default=1, max_length=3, verbose_name='dhcp'),
        ),
    ]
