# Generated by Django 4.1.2 on 2023-11-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0006_alter_redes_dhcp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redes',
            name='ipv6',
        ),
    ]
