# Generated by Django 4.1.2 on 2023-11-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0007_remove_redes_ipv6'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachinelist',
            name='estado',
            field=models.SmallIntegerField(default=0, verbose_name='estado'),
        ),
    ]
