# Generated by Django 4.1.2 on 2025-05-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0008_virtualmachinelist_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillausuarios',
            name='dni',
        ),
    ]
